# DWBI Week 1 — Task 1: The Messy Sales Log
**Python solution | Name: __________________ | Roll number: __________________**

**Result: Rs 6,320 in net Beverages revenue for the morning of 12 September 2026.**

This notebook answers Task 1 only: evidence of data problems, one owner per problem, a traceable revenue calculation, confidence, and prevention at data entry. Run the cells from top to bottom in Jupyter or Google Colab. Only `pandas` is required (`%pip install pandas` if needed).

Sources: the supplied `TASKS(1).md`, `DWBI_W1_Messy_Sales_Log(2).csv`, and the `SEEDED`, `DATES` and `CATALOGUE` definitions in `generate_week1_data(3).py`. The generator is inspected, not executed or changed. The regional Excel workbook belongs to Task 5 and is not needed here. An exact text snapshot of the CSV is embedded so the notebook runs without additional files.

In [1]:
import pandas as pd
from io import StringIO
from IPython.display import display
pd.set_option('display.max_rows', 50)
pd.set_option('display.max_colwidth', 100)

# Raw values stay as strings so formatting problems and empty fields remain visible.
CSV_TEXT = 'OrderID,Branch,Date,Product,Category,Qty,Amount\n1001,LHR-Gulberg,12/09/2026,Cola 1.5L,Beverages,2,360\n1002,Lahore Gulberg,2026-09-12,CL-150,Bev.,1,Rs 180\n1003,KHI-Clifton,09-12-2026,Cola 1.5 Ltr,Beverages,3,540\n1004,ISB-F7,12 Sep 26,Masala Chips 50g,Snacks,4,200\n1004,ISB-F7,12 Sep 26,Masala Chips 50g,Snacks,4,200\n1005,khi clifton,12/09/2026,Fresh Milk 1L,,2,440\n1006,LHR-Gulberg,2026-09-12,Basmati Rice 5kg,Grocery,1,"2,450"\n1007,ISB-F7,12/09/2026,LED Bulb 12W,Electrical,-1,-350\n1008,Lahore Gulberg,12/09/2026,Cola 1.5L,Beverages,2,3600\n1009,ISB F-7,2026/09/12,Yogurt 500g,Dairy,3,510\n1010,Lahore Gulberg,2026-09-12,Orange Juice 1L,Beverages,1,320\n1011,LHR-Gulberg,12/09/2026,LED Bulb 12W,Electrical,1,350\n1012,ISB-F7,2026-09-12,Salted Biscuits Pack,Snacks,5,600\n1013,Lahore Gulberg,12 Sep 26,Cooking Oil 5L,grocery,5,"9,450"\n1014,KHI-Clifton,12/09/2026,Masala Chips 50g,snacks,2,100\n1015,ISB-F7,09-12-2026,Orange Juice 1L,Bev.,3,960\n1016,khi clifton,12/09/2026,LED Bulb 12W,Electronics,1,350\n1017,Lahore Gulberg,09-12-2026,Salted Biscuits Pack,Snacks,1,Rs 120\n1018,KHI-Clifton,2026-09-12,OJ-1L,Bev.,4,"1,280"\n1019,ISB F-7,12/09/2026,Salted Biscuits Pack,Snacks,3,360\n1020,ISB F-7,2026/09/12,Masala Chips 50g,snacks,4,200\n1021,KHI-Clifton,12 Sep 26,CL-150,Beverages,2,360\n1022,KHI-Clifton,2026-09-12,Salted Biscuits Pack,Snacks,5,600\n1023,ISB-F7,2026/09/12,Cooking Oil 5L,grocery,2,"3,780"\n1024,ISB-F7,12 Sep 26,Basmati Rice 5kg,Grocery,3,"7,350"\n1025,ISB F-7,12 Sep 26,Orange Juice 1L,Bev.,2,640\n1026,ISB-F7,12/09/2026,Basmati Rice 5kg,Grocery,5,12250\n1027,Lahore Gulberg,12 Sep 26,Yogurt 500g,dairy,1,170\n1028,LHR-Gulberg,09-12-2026,LED Bulb 12W,Electrical,2,700\n1029,ISB-F7,12/09/2026,Yogurt 500g,dairy,2,340\n1030,KHI-Clifton,2026-09-12,Cola 1.5L,Beverages,1,180\n1031,LHR-Gulberg,2026/09/12,Orange Juice 1L,Beverages,1,320\n1032,ISB-F7,12 Sep 26,Cooking Oil 5L,Grocery,5,"9,450"\n1033,ISB F-7,09-12-2026,Milk 1 Litre,,4,880\n1034,KHI-Clifton,12/09/2026,Orange Juice 1L,Beverages,2,640\n1035,LHR-Gulberg,2026-09-12,Cola 1.5L,Beverages,1,180\n1036,KHI-Clifton,12 Sep 26,Yogurt 500g,Dairy,1,170\n1037,Lahore Gulberg,12/09/2026,Cooking Oil 5L,grocery,2,3780\n'
raw = pd.read_csv(StringIO(CSV_TEXT), dtype=str, keep_default_na=False)
original = raw.copy(deep=True)
print(f"Rows: {len(raw)} | Unique OrderIDs: {raw['OrderID'].nunique()}")
display(raw)

Rows: 38 | Unique OrderIDs: 37

   OrderID          Branch        Date  ...     Category Qty  Amount
0     1001     LHR-Gulberg  12/09/2026  ...    Beverages   2     360
1     1002  Lahore Gulberg  2026-09-12  ...         Bev.   1  Rs 180
2     1003     KHI-Clifton  09-12-2026  ...    Beverages   3     540
3     1004          ISB-F7   12 Sep 26  ...       Snacks   4     200
4     1004          ISB-F7   12 Sep 26  ...       Snacks   4     200
5     1005     khi clifton  12/09/2026  ...                2     440
6     1006     LHR-Gulberg  2026-09-12  ...      Grocery   1   2,450
7     1007          ISB-F7  12/09/2026  ...   Electrical  -1    -350
8     1008  Lahore Gulberg  12/09/2026  ...    Beverages   2    3600
9     1009         ISB F-7  2026/09/12  ...        Dairy   3     510
10    1010  Lahore Gulberg  2026-09-12  ...    Beverages   1     320
11    1011     LHR-Gulberg  12/09/2026  ...   Electrical   1     350
12    1012          ISB-F7  2026-09-12  ...       Snacks   5     600
13    1013  Lahore Gulberg   12 Sep 26  ...      grocery   5   9,450
14    1014     KHI-Clifton  12/09/2026  ...       snacks   2     100
15    1015          ISB-F7  09-12-2026  ...         Bev.   3     960
16    1016     khi clifton  12/09/2026  ...  Electronics   1     350
17    1017  Lahore Gulberg  09-12-2026  ...       Snacks   1  Rs 120
18    1018     KHI-Clifton  2026-09-12  ...         Bev.   4   1,280
19    1019         ISB F-7  12/09/2026  ...       Snacks   3     360
20    1020         ISB F-7  2026/09/12  ...       snacks   4     200
21    1021     KHI-Clifton   12 Sep 26  ...    Beverages   2     360
22    1022     KHI-Clifton  2026-09-12  ...       Snacks   5     600
23    1023          ISB-F7  2026/09/12  ...      grocery   2   3,780
24    1024          ISB-F7   12 Sep 26  ...      Grocery   3   7,350
25    1025         ISB F-7   12 Sep 26  ...         Bev.   2     640
26    1026          ISB-F7  12/09/2026  ...      Grocery   5   12250
27    1027  Lahore Gulberg   12 Sep 26  ...        dairy   1     170
28    1028     LHR-Gulberg  09-12-2026  ...   Electrical   2     700
29    1029          ISB-F7  12/09/2026  ...        dairy   2     340
30    1030     KHI-Clifton  2026-09-12  ...    Beverages   1     180
31    1031     LHR-Gulberg  2026/09/12  ...    Beverages   1     320
32    1032          ISB-F7   12 Sep 26  ...      Grocery   5   9,450
33    1033         ISB F-7  09-12-2026  ...                4     880
34    1034     KHI-Clifton  12/09/2026  ...    Beverages   2     640
35    1035     LHR-Gulberg  2026-09-12  ...    Beverages   1     180
36    1036     KHI-Clifton   12 Sep 26  ...        Dairy   1     170
37    1037  Lahore Gulberg  12/09/2026  ...      grocery   2    3780

[38 rows x 7 columns]

## 1. Find the problems and assign one owner

Each row below has exactly one accountable owner. Applying a correction in Python does not transfer ownership of the underlying decision to ETL. Negative quantities are not automatically errors: the problem is the missing return context and reporting rule.

In [2]:
issues = [['Branch aliases', '1002', 'Lahore Gulberg vs LHR-Gulberg (1001); 6 labels represent 3 branches.', 'Branch totals split across aliases.', 'ETL / staging', 'Use a documented alias-to-branch mapping because these names can be standardized consistently.'], ['Mixed and ambiguous dates', '1003', '09-12-2026 vs 12/09/2026 (1001); 5 raw formats.', 'Automatic parsing can put September sales in December or fail.', 'ETL / staging', 'Apply explicit source-specific formats; the task and generator establish a single morning.'], ['Exact duplicate order', '1004', 'The entire Snacks row appears twice, Rs 200 each.', 'Sales and quantities are counted twice.', 'Source system', 'Make posting/export idempotent with a unique transaction-line key so replay cannot create another row.'], ['Product aliases', '1002', 'CL-150, Cola 1.5L (1001) and Cola 1.5 Ltr (1003) are the same product.', 'Product totals split and price comparisons miss equivalent products.', 'ETL / staging', 'Map the aliases to the canonical catalogue product.'], ['Category case and abbreviations', '1002', 'Bev. vs Beverages; snacks (1014) vs Snacks.', 'An exact Beverages filter omits valid sales.', 'ETL / staging', 'Normalize case and map documented abbreviations consistently.'], ['Missing categories', '1005', 'Fresh Milk 1L has no category; order 1033 also has a blank.', 'Category reports silently exclude or misclassify Rs 1,320.', 'The business', 'The catalogue owner defines milk as Dairy; ETL then applies that approved classification.'], ['Conflicting category names', '1016', 'LED Bulb 12W is Electronics here but Electrical at 1011.', 'One product appears in two departments.', 'The business', 'Approve one category taxonomy; use Electronics from the supplied catalogue for this exercise.'], ['Amounts contain formatting text', '1002', 'Rs 180 is text; order 1018 contains 1,280.', 'Numeric conversion fails or silently drops valid revenue.', 'ETL / staging', 'Remove documented currency prefixes and grouping commas, then reject any unparseable value.'], ['Return lacks transaction context', '1007', 'LED Bulb 12W has Qty -1 and Amount -350, without a return flag or original-sale link.', 'Deleting negatives inflates net sales; the return period is unclear.', 'The business', 'Define net versus gross revenue and return recognition; retain it as a current-period return here.'], ['Incorrect line amount', '1008', '2 cola bottles cost 3,600, versus 360 for the same quantity at 1001.', 'Beverages revenue is inflated by Rs 3,240.', 'Source system', 'Calculate the amount from the approved unit price and quantity; prevent unchecked amount overrides.']]
issue_table = pd.DataFrame(issues, columns=['Problem','Example OrderID','Evidence','Report impact','Owner','Ownership justification'])
display(issue_table)
print('Distinct problems:', len(issue_table))

                            Problem  ...                                                                              Ownership justification
0                    Branch aliases  ...       Use a documented alias-to-branch mapping because these names can be standardized consistently.
1         Mixed and ambiguous dates  ...           Apply explicit source-specific formats; the task and generator establish a single morning.
2             Exact duplicate order  ...  Make posting/export idempotent with a unique transaction-line key so replay cannot create anothe...
3                   Product aliases  ...                                                  Map the aliases to the canonical catalogue product.
4   Category case and abbreviations  ...                                        Normalize case and map documented abbreviations consistently.
5                Missing categories  ...            The catalogue owner defines milk as Dairy; ETL then applies that approved classification.
6        Conflicting category names  ...        Approve one category taxonomy; use Electronics from the supplied catalogue for this exercise.
7   Amounts contain formatting text  ...          Remove documented currency prefixes and grouping commas, then reject any unparseable value.
8  Return lacks transaction context  ...   Define net versus gross revenue and return recognition; retain it as a current-period return here.
9             Incorrect line amount  ...  Calculate the amount from the approved unit price and quantity; prevent unchecked amount overrides.

[10 rows x 6 columns]

Distinct problems: 10

In [3]:
print('Branch labels:', sorted(raw['Branch'].unique()))
print('Date strings:', sorted(raw['Date'].unique()))
print('Category labels:', sorted(raw['Category'].unique()))
print('\nExact duplicate rows:')
display(raw.loc[raw.duplicated(keep=False)])
print('Blank categories:')
display(raw.loc[raw['Category'].eq('')])
print('Non-numeric amount strings before cleaning:')
display(raw.loc[pd.to_numeric(raw['Amount'], errors='coerce').isna(), ['OrderID','Amount']])

Branch labels: ['ISB F-7', 'ISB-F7', 'KHI-Clifton', 'LHR-Gulberg', 'Lahore Gulberg', 'khi clifton']
Date strings: ['09-12-2026', '12 Sep 26', '12/09/2026', '2026-09-12', '2026/09/12']
Category labels: ['', 'Bev.', 'Beverages', 'Dairy', 'Electrical', 'Electronics', 'Grocery', 'Snacks', 'dairy', 'grocery', 'snacks']

Exact duplicate rows:

  OrderID  Branch       Date           Product Category Qty Amount
3    1004  ISB-F7  12 Sep 26  Masala Chips 50g   Snacks   4    200
4    1004  ISB-F7  12 Sep 26  Masala Chips 50g   Snacks   4    200

Blank categories:

   OrderID       Branch        Date        Product Category Qty Amount
5     1005  khi clifton  12/09/2026  Fresh Milk 1L            2    440
33    1033      ISB F-7  09-12-2026   Milk 1 Litre            4    880

Non-numeric amount strings before cleaning:

   OrderID  Amount
1     1002  Rs 180
6     1006   2,450
13    1013   9,450
17    1017  Rs 120
18    1018   1,280
23    1023   3,780
24    1024   7,350
32    1032   9,450

## 2. Decisions and assumptions

- **Scope:** all 38 rows are the stated morning's export. There are no timestamps, so the CSV alone cannot verify the morning cutoff. The five date strings are interpreted as **12 September 2026**, including the ambiguous `09-12-2026`, using the task/generator context rather than a global `dayfirst` guess.
- **Duplicate:** remove only the second exact copy of order 1004. It is Snacks, so this reduces all-category revenue by Rs 200 and Beverages revenue by **Rs 0**. Repeated IDs with different line details would require investigation, not automatic deletion.
- **Blank categories:** classify orders 1005 and 1033 as Dairy using the supplied catalogue. Their Rs 440 + Rs 880 = **Rs 1,320** remains outside Beverages. Effect on Beverages: **Rs 0**.
- **Return:** use net revenue and retain order 1007 at **−Rs 350**. It is an Electronics return, so its effect on Beverages is **Rs 0**. Do not turn the amount positive or discard it.
- **Amount error:** choose order 1001 as correct. It implies Rs 180 per cola bottle; orders 1002, 1003, 1021, 1030 and 1035 corroborate that price. The generator explicitly identifies 1008 as erroneous and gives a unit price of Rs 180. Correct 1008 from Rs 3,600 to **2 × Rs 180 = Rs 360**, decreasing Beverages by **Rs 3,240**.
- **Metric:** sum line `Amount`, which already includes quantity. Do not multiply it by `Qty` again. Treat amounts as PKR; no extra taxes or discounts are invented.

In [4]:
# Parse amounts strictly after removing only the observed formatting.
work = raw.copy()
work['Amount_num'] = pd.to_numeric(
    work['Amount'].str.replace(r'^Rs\s*', '', regex=True).str.replace(',', '', regex=False),
    errors='raise'
)
work['Qty_num'] = pd.to_numeric(work['Qty'], errors='raise')
branch_map = {'LHR-Gulberg':'Lahore Gulberg', 'Lahore Gulberg':'Lahore Gulberg',
              'KHI-Clifton':'Karachi Clifton', 'khi clifton':'Karachi Clifton',
              'ISB-F7':'Islamabad F-7', 'ISB F-7':'Islamabad F-7'}
product_aliases = {'CL-150':'Cola 1.5L', 'Cola 1.5 Ltr':'Cola 1.5L',
                   'OJ-1L':'Orange Juice 1L', 'Milk 1 Litre':'Fresh Milk 1L'}
category_map = {'beverages':'Beverages', 'bev.':'Beverages', 'snacks':'Snacks',
                'dairy':'Dairy', 'grocery':'Grocery',
                'electrical':'Electronics', 'electronics':'Electronics'}
work['Branch_clean'] = work['Branch'].map(branch_map)
work['Product_clean'] = work['Product'].replace(product_aliases)
work['Category_clean'] = work['Category'].str.strip().str.lower().map(category_map)
# Explicit interpretations documented above; do not generalize this to other exports.
date_formats = {'12/09/2026':'%d/%m/%Y', '2026-09-12':'%Y-%m-%d',
                '09-12-2026':'%m-%d-%Y', '12 Sep 26':'%d %b %y', '2026/09/12':'%Y/%m/%d'}
work['Date_clean'] = work['Date'].map(lambda s: pd.to_datetime(s, format=date_formats[s]))

# Deduplicate using every original column, never just the order ID.
clean = work.loc[~raw.duplicated()].copy()
missing_category = clean['Category'].eq('')
clean.loc[missing_category, 'Category_clean'] = clean.loc[missing_category, 'Product_clean'].map({'Fresh Milk 1L':'Dairy'})
clean['Amount_clean'] = clean['Amount_num']
clean.loc[clean['OrderID'].eq('1008'), 'Amount_clean'] = 2 * 180

print('Cola price evidence before correction:')
cola = clean.loc[clean['Product_clean'].eq('Cola 1.5L'), ['OrderID','Qty_num','Amount_num']].copy()
cola['Implied_unit_price'] = cola['Amount_num'] / cola['Qty_num']
display(cola)
print(f"Clean rows: {len(clean)} | Branches: {clean['Branch_clean'].nunique()}")

Cola price evidence before correction:

   OrderID  Qty_num  Amount_num  Implied_unit_price
0     1001        2         360               180.0
1     1002        1         180               180.0
2     1003        3         540               180.0
8     1008        2        3600              1800.0
21    1021        2         360               180.0
30    1030        1         180               180.0
35    1035        1         180               180.0

Clean rows: 37 | Branches: 3

## 3. Beverages revenue — calculation and reconciliation

Start with a deliberately incomplete exact-label total after safely parsing amounts. Add the sales labelled `Bev.`, then apply the documented decisions. This shows why getting a numeric sum alone is not enough.

In [5]:
baseline = work.loc[work['Category'].eq('Beverages'), 'Amount_num'].sum()
alias_addition = work.loc[work['Category'].eq('Bev.'), 'Amount_num'].sum()
bridge = pd.DataFrame([
    ['Parsed amounts; exact Beverages label only', baseline],
    ['Include Bev. orders 1002, 1015, 1018, 1025', alias_addition],
    ['Remove duplicate 1004 (Snacks)', 0],
    ['Classify 1005 and 1033 as Dairy', 0],
    ['Retain return 1007 (Electronics)', 0],
    ['Correct order 1008: 360 minus 3,600', 360-3600],
], columns=['Step','Effect_PKR'])
bridge['Running_total_PKR'] = bridge['Effect_PKR'].cumsum()
display(bridge)

beverages = clean.loc[clean['Category_clean'].eq('Beverages')].copy()
display(beverages[['OrderID','Branch_clean','Product_clean','Qty_num','Amount','Amount_clean']])
revenue = beverages['Amount_clean'].sum()
print('Working:', ' + '.join(beverages['Amount_clean'].astype(str)), '=', revenue)
print(f'TOTAL NET BEVERAGES REVENUE: Rs {revenue:,.0f}')
print('\nBy product:')
display(beverages.groupby('Product_clean', as_index=False)['Amount_clean'].sum())
print('By branch:')
display(beverages.groupby('Branch_clean', as_index=False)['Amount_clean'].sum())

                                         Step  Effect_PKR  Running_total_PKR
0  Parsed amounts; exact Beverages label only        6500               6500
1  Include Bev. orders 1002, 1015, 1018, 1025        3060               9560
2              Remove duplicate 1004 (Snacks)           0               9560
3             Classify 1005 and 1033 as Dairy           0               9560
4            Retain return 1007 (Electronics)           0               9560
5         Correct order 1008: 360 minus 3,600       -3240               6320

   OrderID     Branch_clean    Product_clean  Qty_num  Amount  Amount_clean
0     1001   Lahore Gulberg        Cola 1.5L        2     360           360
1     1002   Lahore Gulberg        Cola 1.5L        1  Rs 180           180
2     1003  Karachi Clifton        Cola 1.5L        3     540           540
8     1008   Lahore Gulberg        Cola 1.5L        2    3600           360
10    1010   Lahore Gulberg  Orange Juice 1L        1     320           320
15    1015    Islamabad F-7  Orange Juice 1L        3     960           960
18    1018  Karachi Clifton  Orange Juice 1L        4   1,280          1280
21    1021  Karachi Clifton        Cola 1.5L        2     360           360
25    1025    Islamabad F-7  Orange Juice 1L        2     640           640
30    1030  Karachi Clifton        Cola 1.5L        1     180           180
31    1031   Lahore Gulberg  Orange Juice 1L        1     320           320
34    1034  Karachi Clifton  Orange Juice 1L        2     640           640
35    1035   Lahore Gulberg        Cola 1.5L        1     180           180

Working: 360 + 180 + 540 + 360 + 320 + 960 + 1280 + 360 + 640 + 180 + 320 + 640 + 180 = 6320
TOTAL NET BEVERAGES REVENUE: Rs 6,320

By product:

     Product_clean  Amount_clean
0        Cola 1.5L          2160
1  Orange Juice 1L          4160

By branch:

      Branch_clean  Amount_clean
0    Islamabad F-7          1600
1  Karachi Clifton          3000
2   Lahore Gulberg          1720

### Why amount parsing matters

`pd.to_numeric(..., errors='coerce')` on the raw field silently converts `Rs 180` and `1,280` to missing values. Both are Beverages orders. The following demonstration measures the resulting **Rs 1,460** understatement before correcting 1008.

In [6]:
beverage_labels = work['Category'].isin(['Beverages', 'Bev.'])
naive = pd.to_numeric(raw['Amount'], errors='coerce')
print('Beverages with silently skipped amount strings:', naive.loc[beverage_labels].sum())
print('Beverages after safe amount parsing, before amount correction:', work.loc[beverage_labels, 'Amount_num'].sum())
print('Revenue silently skipped:', work.loc[beverage_labels, 'Amount_num'].sum() - naive.loc[beverage_labels].sum())

# Reconcile the result with independently stated catalogue prices.
expected_prices = {'Cola 1.5L':180, 'Orange Juice 1L':320}
independent_total = (beverages['Qty_num'] * beverages['Product_clean'].map(expected_prices)).sum()
assert revenue == independent_total == bridge['Running_total_PKR'].iloc[-1] == 6320
assert len(raw) == 38 and len(clean) == 37
assert clean['Branch_clean'].nunique() == 3
assert clean[['Branch_clean','Category_clean','Date_clean']].notna().all().all()
assert clean['Date_clean'].eq(pd.Timestamp('2026-09-12')).all()
assert clean.loc[clean['OrderID'].eq('1007'), 'Amount_clean'].iloc[0] == -350
assert clean['Amount_clean'].sum() == work['Amount_num'].sum() - 200 - 3240
assert raw.equals(original)
print('Checks passed: revenue reconciles, duplicate removed, return retained, raw data unchanged.')

Beverages with silently skipped amount strings: 8100.0
Beverages after safe amount parsing, before amount correction: 9560
Revenue silently skipped: 1460.0
Checks passed: revenue reconciles, duplicate removed, return retained, raw data unchanged.

## 4. Confidence level

**Medium for an operational report.** The arithmetic is reproducible, and the supplied generator strongly supports the correction and product classifications. However, the CSV has no times, receipt references, approved return policy, or evidence that every order from all branches was exported. These limitations prevent treating it as independently verified morning revenue.

To raise confidence to **high**, obtain the original receipt for order 1008, the approved product/category and price master, source date-format specifications and transaction timestamps, and branch reconciliation totals showing that the export is complete and covers the morning cutoff. Confirm the return policy and unique transaction-line identifiers. For this teaching dataset, the generator already confirms the intended price correction and milk classification.

## 5. Why not load it directly into a dashboard?

Loading this file unchanged would split identical branches and products, omit valid Beverages amounts, double-count a duplicate, and overstate one sale, producing a misleading dashboard even when its charts look correct.

## 6. Two problems preventable at data entry

| Problem | Example | One change to the branch system |
|---|---|---|
| Wrong line amount | Order 1008 records Rs 3,600 instead of Rs 360. | Make line amount a system-calculated field based on quantity and the approved product price, with any override requiring authorization. |
| Duplicate transaction | Order 1004 appears twice. | Enforce an idempotent transaction-line key so a repeated submission returns the original record instead of creating another one. |

**Final answer:** net Beverages revenue for the stated morning is **Rs 6,320**, under the explicit decisions above.